apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: daniel-lazar-eu-tls
spec:
  secretName: daniel-lazar-eu
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: daniel-lazar.eu
  dnsNames:
    - daniel-lazar.eu
    - www.daniel-lazar.eu
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - daniel-lazar.eu
          - www.daniel-lazar.eu