apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec: 
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'daniel__lazar@t-online.de'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}